### ISSUE TITLE
Unable to access the Solr server

### ISSUE THREAD

**Issue by SouzaJBR** [SmartDataAnalytics/DeFacto#35]
Hello there

I'm facing an issue while trying to run a validation. Just like in #33, i get the message '400 Bad Request Wrong input'. However, it seems to be something related to Solr queries. When I run one of the examples, i face this exception:

```Defacto_1     | 14:01:33 DEBUG [http-nio-4441-exec-6] - [PoolingClientConnectionManager]- Connection released: [id: 7][route: {}->http://139.18.2.164:8080][total kept alive: 0; route allocated: 0 of 32; total allocated: 0 of 128]
Defacto_1     | org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://139.18.2.164:8080/solr/factbench_topicterms
Defacto_1     |         at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:559)
Defacto_1     |         at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
Defacto_1     |         at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
...
```

Is there any other Solr server available for DeFacto? 

PS: running with Docker compose

**Comment by diegoesteves** [comment]
Hi João,

Sorry, we no longer keep the solr server live. I will try to find a way to share the data with you via e.g, FTP. Please send me an email: myusername.replace('br', '') + gmail ;-)

**Comment by diegoesteves** [comment]
BTW, back then the data was indexed using solr 4.5. In case you work on it and e.g., update the indexes to a more recent version (e.g., elasticsearch 7 or so) I can guide you through the data schema part. I think it would be great to share with the research community afterwards.
